"""empty message

Revision ID: 8251075cfa2a
Revises: None
Create Date: 2019-03-20 09:17:09.406545

"""

# revision identifiers, used by Alembic.
revision = '8251075cfa2a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('price_sqm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('living_area_sqm', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartment')
    # ### end Alembic commands ###
